# Generated by Django 4.1.3 on 2023-02-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
