# Generated by Django 4.1.3 on 2023-02-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0003_noticia_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='img',
        ),
    ]
