# Generated by Django 4.1.3 on 2023-02-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0004_remove_noticia_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/noticias'),
        ),
    ]
