# Generated by Django 4.1.3 on 2023-02-18 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria_app', '0005_noticia_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
