# Generated by Django 4.1.3 on 2023-02-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0006_rename_title_noticia_titulo_alter_noticia_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='text',
            new_name='texto',
        ),
    ]
