# Generated by Django 4.1.3 on 2023-02-18 23:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria_app', '0007_rename_author_noticia_autor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Artworks',
        ),
    ]
