# Generated by Django 4.1.3 on 2023-02-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0010_remove_artwork_published_date_alter_artwork_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='created_date',
            new_name='fecha_de_creacion',
        ),
    ]
