# Generated by Django 4.1.3 on 2023-03-06 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0012_categoria_artwork_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='video',
            field=models.FileField(blank=True, help_text='Seleccione un video para mostrar', null=True, upload_to='Videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='categoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='galeria_app.categoria'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='img',
            field=models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='Artworks/%Y/%m/%d'),
        ),
    ]
